import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class PeliculasService {
  url = 'https://api.themoviedb.org/3/list/2?api_key=d30a9009321eae916db3a03631a903de';
  peliculas = [
    { "genre_ids": ['Action', 'Comedy', 'Romance'], "id": 74643, "original_title": "The Artist", "overview": "Hollywood, 1927: As silent movie star George Valentin wonders if the arrival of talking pictures will cause him to fade into oblivion, he sparks with Peppy Miller, a young dancer set for a big break.", "popularity": 11.138, "poster_path": "https://image.tmdb.org/t/p/w500//khtVL4abxYczXAWbo1wAz13CLx3.jpg", "release_date": "2011-10-08" },
    { "genre_ids": ['Comedy', 'Action'], "id": 65057, "media_type": "movie", "original_language": "en", "original_title": "The Descendants", "overview": "With his wife Elizabeth on life support after a boating accident, Hawaiian land baron, Matt King takes his daughters on a trip from Oahu to Kauai to confront a young real estate broker, who was having an affair with Elizabeth before her misfortune.", "popularity": 16.193, "poster_path": "https://image.tmdb.org/t/p/w500//mCpYsKQNOtaBYJWCRYYuFmLsB6X.jpg", "release_date": "2011-09-09" },
    { "genre_ids": ['Action'], "id": 64685, "media_type": "movie", "original_language": "en", "original_title": "Extremely Loud & Incredibly Close", "overview": "A year after his father's death, Oskar, a troubled young boy, discovers a mysterious key he believes was left for him by his father and embarks on a scavenger hunt to find the matching lock.", "popularity": 15.987, "poster_path": "https://image.tmdb.org/t/p/w500//6pszViNvKr1r31pP7gJNYDHEx5P.jpg", "release_date": "2011-12-24" },
    { "genre_ids": ['Action'], "id": 50014, "media_type": "movie", "original_language": "en", "original_title": "The Help", "overview": "Aibileen Clark is a middle-aged African-American maid who has spent her life raising white children and has recently lost her only son; Minny Jackson is an African-American maid who has often offended her employers despite her family's struggles with money and her desperate need for jobs; and Eugenia \"Skeeter\" Phelan is a young white woman who has recently moved back home after graduating college to find out her childhood maid has mysteriously disappeared. These three stories intertwine to explain how life in Jackson, Mississippi revolves around \"the help\"; yet they are always kept at a certain distance because of racial lines.", "popularity": 20.239, "poster_path": "https://image.tmdb.org/t/p/w500//7XLSwxpfpPoJyTdJVot6a42TS2V.jpg", "release_date": "2011-08-09" },
    { "genre_ids": ['Adventure', 'Action', 'Family'], "id": 44826, "media_type": "movie", "original_language": "en", "original_title": "Hugo", "overview": "Orphaned and alone except for an uncle, Hugo Cabret lives in the walls of a train station in 1930s Paris. Hugo's job is to oil and maintain the station's clocks, but to him, his more important task is to protect a broken automaton and notebook left to him by his late father. Accompanied by the goddaughter of an embittered toy merchant, Hugo embarks on a quest to solve the mystery of the automaton and find a place he can call home.", "popularity": 24.425, "poster_path": "https://image.tmdb.org/t/p/w500//vDAhBTIHvIoNOlgCfmLirVgUK2p.jpg", "release_date": "2011-11-22" },
    { "genre_ids": ['Fantasy', 'Comedy', 'Romance'], "id": 59436, "media_type": "movie", "original_language": "en", "original_title": "Midnight in Paris", "overview": "A romantic comedy about a family traveling to the French capital for business. The party includes a young engaged couple forced to confront the illusion that a life different from their own is better.", "popularity": 17.695, "poster_path": "https://image.tmdb.org/t/p/w500//4wBG5kbfagTQclETblPRRGihk0I.jpg", "release_date": "2011-05-11" },
    { "genre_ids": ['Action'], "id": 60308, "media_type": "movie", "original_language": "en", "original_title": "Moneyball", "overview": "The story of Oakland Athletics general manager Billy Beane's successful attempt to put together a baseball team on a budget, by employing computer-generated analysis to draft his players.", "popularity": 17.997, "poster_path": "https://image.tmdb.org/t/p/w500//4yIQq1e6iOcaZ5rLDG3lZBP3j7a.jpg", "release_date": "2011-09-22" },
    { "genre_ids": ['Action', 'Fantasy'], "id": 8967, "media_type": "movie", "original_language": "en", "original_title": "The Tree of Life", "overview": "The impressionistic story of a Texas family in the 1950s. The film follows the life journey of the eldest son, Jack, through the innocence of childhood to his disillusioned adult years as he tries to reconcile a complicated relationship with his father. Jack finds himself a lost soul in the modern world, seeking answers to the origins and meaning of life while questioning the existence of faith.", "popularity": 12.885, "poster_path": "https://image.tmdb.org/t/p/w500//l8cwuB5WJSoj4uMAsnzuHBOMaSJ.jpg", "release_date": "2011-05-17" },
    { "genre_ids": ['Action', 'War', 'Action'], "id": 57212, "media_type": "movie", "original_language": "en", "original_title": "War Horse", "overview": "Follows a young man named Albert and his horse, Joey, and how their bond is broken when Joey is sold to the cavalry and sent to the trenches of World War One. Despite being too young to enlist, Albert heads to France to save his friend.", "popularity": 20.931, "poster_path": "https://image.tmdb.org/t/p/w500//7KHz6JlJhrFAPesmUkgdnLrSr8Y.jpg", "release_date": "2011-12-25" }];

  constructor(private http: HttpClient) { }

  getPeliculas() {
    return this.http.get(this.url);
  }
}
